# **Marshall Tuck's ethnocentrism contradicts Californian values**

[Business banker](https://capitalandmain.com/a-great-divide-the-election-fight-for-californias-schools) Marshall Tuck is running for California State Superintendent of Public Instruction again. He's backed by the same ideologically charged billionaires as the last time — several of whom supported reactionary measures like [Proposition 8](http://progressive.org/public-school-shakedown/california-school-superintendent-candidate-is-tied-to-anti-g_180208/). With nearly unlimited funding, voters will be deluged with Tuck's messaging. There'll be plenty of unsubstantiated claims that he ran successful schools.

Those ads won’t reveal the truth about Tuck’s record. There’ll be no mention that when he ran the Green Dot Charter Corporation, one of his high schools “achieved” the dubious distinction of [back](http://asd.calstate.edu/performance/elm-ept/2005/scripts/hsrem05.asp?campus=199658)-to-[back](http://asd.calstate.edu/performance/elm-ept/2006/scripts/hsrem06.asp?campus=199658) years of absolutely zero students scoring proficient on the mathematics portion of the California State University (CSU) entrance examination. There won’t be discussion of how, under Tuck, one Partnership for Los Angeles Schools’ (PLAS) high school went [five years](http://thewire.k12newsnetwork.com/2018/10/20/under-marshall-tuck-jordan-hs-went-five-years-with-under-20-of-students-scoring-proficient-for-csu/) without achieving even twenty percent of students scoring proficient on either the mathematics or the English portion of those same CSU exams. Five years. These awful proficiency rates were reflected in Scholastic Aptitude Tests (SAT) scores as well. Under Tuck’s “leadership” the schools he managed were among the [very lowest scorers](http://thewire.k12newsnetwork.com/2014/08/22/marshall-tuck-run-schools-sat-scores-remained-flat-some-even-declined/) on the SAT in Los Angeles County, year after year.

Tuck's record of terrible academic results isn't the only issue that will be carefully obscured. His abject treatment of students of color, in a fashion much like his contemporary counterparts Tom Horne and John Huppenthal in Arizona, is something he works hard to hide. It's time to shine a bright light on this.

Using their positions of authority, Tuck, Horne, and Huppenthal closed down popular, [research proven](http://www.nea.org/assets/docs/NBI-2010-3-value-of-ethnic-studies.pdf), Ethnic Studies programs. Tuck did it at PLAS schools like [Santee High School](http://www.schoolsmatter.info/2012/07/mayor-villaraigosa-and-plas-ceo-tuck.html) when he was their "CEO." The other two did it while they were Superintendents of Public Schools in [Arizona](https://www.azcentral.com/story/news/local/arizona/2017/07/18/former-az-school-chief-tom-horne-testify-mexican-american-studies-trial/486558001/). Tuck went a step further than the others — he also [restricted and shuttered](http://thewire.k12newsnetwork.com/2017/05/03/a-year-of-observation-on-plas-and-marshall-tuck/) both Heritage Language Programs and Dual Language Immersion programs. These important language programs were well regarded and research proven. The language program closures and restrictions were so egregious that a [Uniform Complaint Cause of Action](https://www.scribd.com/doc/243731079/smoking-gun-marshall-tuck-violated-student-and-parent-civil-rights) was filed jointly by Mexican American Legal Defense and Educational Fund and Public Counsel Law Center on behalf of the families whose civil rights Tuck violated.  Additionally, Tuck closed down other critical programs including [health education](http://articles.latimes.com/2012/may/20/local/la-me-lausd-health-20120521).

In the end, after a long battle, Horne and Huppenthal’s attacks on students of color by eliminating Ethnic Studies in Arizona were defeated in court. The judge's [opinion noted](https://rewire.news/ablc/2017/08/24/federal-court-unmoved-arizona-school-officials-hurt-white-feelings/) that the two were “capitalizing on race-based fears.” Both politicians would later find themselves [voted out](https://tucson.com/laestrella/noticias/sarah-garrecht-gassen-adios-horne-and-huppenthal/article_05dac216-3771-5056-b768-8841a36a57de.html) of office. Tuck, whose record on these programs mirrors that of Horne and Huppenthal, is facing a California with very different values than his. In 2016, in contradiction to Tuck’s penchant for opposing bilingualism, Californian voters passed [Proposition 58](http://www.latimes.com/opinion/editorials/la-ed-proposition-58-20160906-snap-story.html) — reestablishing bilingualism as mainstream. Furthermore, [school districts](http://www.latimes.com/local/education/la-me-ethnic-studies-20141209-story.html) have been passing resolutions instituting Ethnic Studies programs. On the state level advances for Ethnic Studies like [AB-2016](https://www.nbcnews.com/news/asian-america/california-governor-signs-bill-develop-high-school-ethnic-studies-curriculum-n648396) have proven that Californians don’t share Tuck’s aversion to programs that celebrate diversity and encourage youth to explore their history.

Defeating Horne and Huppenthal's attacks on students of color required protracted court battles. Californians can avoid these same problems by rejecting Marshall Tuck and his policies. In the current political atmosphere, where bigotry and ethnocentrism must be opposed at every turn, Californians should send a powerful message in support of our students. We can do that by electing Tony Thurmond.

*Robert D. Skeels, an education researcher, holds a BA from UCLA and a JD from PCL*
